# Generated by Django 5.1.4 on 2024-12-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "lecturer", "managed": False,},
        ),
        migrations.CreateModel(
            name="LecturerRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "lecturer_rating", "managed": False,},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("gender", models.CharField(blank=True, max_length=80, null=True)),
                ("nationality", models.CharField(blank=True, max_length=80, null=True)),
                ("occupy", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "graduated_university",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "accumulated_online_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dob", models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={"db_table": "student", "managed": False,},
        ),
    ]
