# Generated by Django 5.1.4 on 2024-12-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_lecturer_options_alter_lecturerrating_options_and_more"),
    ]

    operations = []
