# Generated by Django 5.1.4 on 2024-12-24 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_subject_options"),
        ("users", "0003_initial_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_column="account",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lecturerrating",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                db_column="lecturer",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="lecturerrating",
            name="student",
            field=models.ForeignKey(
                blank=True,
                db_column="student",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_column="account",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                blank=True,
                db_column="course",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lecturerrating",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
