# Generated by Django 5.1.4 on 2024-12-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_category_table_alter_course_table"),
    ]

    operations = [
        migrations.AlterModelOptions(name="subject", options={},),
    ]
