# Generated by Django 5.1.4 on 2024-12-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_subject_options"),
    ]

    operations = []
