# Generated by Django 5.1.4 on 2024-12-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_initial_data"),
    ]

    operations = [
        migrations.AlterModelOptions(name="subject", options={"managed": False},),
    ]
